# Generated by Django 4.2.5 on 2024-09-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_cartitem_create_at_alter_cartitem_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='order_quantity',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
