# Generated by Django 4.2.5 on 2024-09-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_quantity_cartitem_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='order_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
