# Generated by Django 4.2.5 on 2024-09-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_availability',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('full_day', 'full_day')], default='full_day', max_length=50),
        ),
    ]
